//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_pp_practice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials()
        {
            this.ProductsMaterials = new HashSet<ProductsMaterials>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> MinQBox { get; set; }
        public Nullable<int> EdiniciID { get; set; }
        public Nullable<int> QSclad { get; set; }
        public Nullable<int> MinVozm { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual Edinici Edinici { get; set; }
        public virtual MaterialTypes MaterialTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsMaterials> ProductsMaterials { get; set; }
    }
}
